server:
  port: 8080
  servlet:
    context-path: /notification.api

spring:
  application:
    name: notification-api

  datasource:
    url: jdbc:postgresql://localhost:5444/notification?currentSchema=api
    username: sdsdsd
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.default_schema: api
      hibernate.format_sql: true
  sql:
    init:
      mode: never

  rabbitmq:
    host: localhost
    port: 5672
    username: noti_user
    password: SomeP4ssw0rd!
    virtual-host: /notification
    listener:
      simple:
        prefetch: 50

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
